### ISSUE TITLE
Jquery being added via http not https

### ISSUE THREAD

**Issue by ptravers** [kittsville/Chomskey#9]
Jquery won't load if page requested via https not http. 

Mixed Content: The page at 'https://kittsville.github.io/Chomskey/' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.
core.js:8 Uncaught ReferenceError: $ is not defined

**Comment by kittsville** [comment]
Tested in latest FF and Chrome with no issue. I'm guessing you're using HTTPS Everywhere. This also raises the issue that Chomskey silently falls flat on its face if jQuery fails to load.

Created connected issue #10

**Comment by kittsville** [comment]
The http/https error no longer occurs but Chomskey will still silently fail if jQuery fails to load. As this issue is being dealt with in another issue (#10) I think it's safe to close this.
